
GET http://localhost:4029/api/group/health-check

###

GET http://localhost:4029/api/group/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJVMiIsImlhdCI6MTYwMTM3Nzk3Mn0.gRGSbpvNVsZxsYl_wp0gCKW6Snc4TzmBMI97PedUEcQ

###

POST http://localhost:4029/api/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJVMiIsImlhdCI6MTYwMTM3Nzk3Mn0.gRGSbpvNVsZxsYl_wp0gCKW6Snc4TzmBMI97PedUEcQ
Content-Type: application/json

{
    "id": "G2",
    "name": "First Updated Group"
}

###


